# Generated by Django 5.2.15 on 2026-09-13 07:35

import core.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionhistory',
            name='download_file',
            field=models.FileField(blank=True, null=True, storage=core.custom_storages.get_private_storage, upload_to='products/files/'),
        ),
    ]
