# Generated by Django 5.2.15 on 2026-09-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='membership_expires',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='membership_type',
        ),
    ]
