# Generated by Django 5.2.15 on 2026-07-05 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
    ]
